HEADERS += \
    ../Classes/Box2DTestBed/Box2dView.h \
    ../Classes/Box2DTestBed/GLES-Render.h \
    ../Classes/Box2DTestBed/Test.h \
    ../Classes/Box2DTestBed/Tests/AddPair.h \
    ../Classes/Box2DTestBed/Tests/ApplyForce.h \
    ../Classes/Box2DTestBed/Tests/BodyTypes.h \
    ../Classes/Box2DTestBed/Tests/Breakable.h \
    ../Classes/Box2DTestBed/Tests/Bridge.h \
    ../Classes/Box2DTestBed/Tests/BulletTest.h \
    ../Classes/Box2DTestBed/Tests/Cantilever.h \
    ../Classes/Box2DTestBed/Tests/Car.h \
    ../Classes/Box2DTestBed/Tests/Chain.h \
    ../Classes/Box2DTestBed/Tests/CharacterCollision.h \
    ../Classes/Box2DTestBed/Tests/CollisionFiltering.h \
    ../Classes/Box2DTestBed/Tests/CollisionProcessing.h \
    ../Classes/Box2DTestBed/Tests/CompoundShapes.h \
    ../Classes/Box2DTestBed/Tests/Confined.h \
    ../Classes/Box2DTestBed/Tests/ContinuousTest.h \
    ../Classes/Box2DTestBed/Tests/ConvexHull.h \
    ../Classes/Box2DTestBed/Tests/ConveyorBelt.h \
    ../Classes/Box2DTestBed/Tests/DistanceTest.h \
    ../Classes/Box2DTestBed/Tests/Dominos.h \
    ../Classes/Box2DTestBed/Tests/DumpShell.h \
    ../Classes/Box2DTestBed/Tests/DynamicTreeTest.h \
    ../Classes/Box2DTestBed/Tests/EdgeShapes.h \
    ../Classes/Box2DTestBed/Tests/EdgeTest.h \
    ../Classes/Box2DTestBed/Tests/Gears.h \
    ../Classes/Box2DTestBed/Tests/Mobile.h \
    ../Classes/Box2DTestBed/Tests/MobileBalanced.h \
    ../Classes/Box2DTestBed/Tests/MotorJoint.h \
    ../Classes/Box2DTestBed/Tests/OneSidedPlatform.h \
    ../Classes/Box2DTestBed/Tests/Pinball.h \
    ../Classes/Box2DTestBed/Tests/PolyCollision.h \
    ../Classes/Box2DTestBed/Tests/PolyShapes.h \
    ../Classes/Box2DTestBed/Tests/Prismatic.h \
    ../Classes/Box2DTestBed/Tests/Pulleys.h \
    ../Classes/Box2DTestBed/Tests/Pyramid.h \
    ../Classes/Box2DTestBed/Tests/RayCast.h \
    ../Classes/Box2DTestBed/Tests/Revolute.h \
    ../Classes/Box2DTestBed/Tests/Rope.h \
    ../Classes/Box2DTestBed/Tests/RopeJoint.h \
    ../Classes/Box2DTestBed/Tests/SensorTest.h \
    ../Classes/Box2DTestBed/Tests/ShapeEditing.h \
    ../Classes/Box2DTestBed/Tests/SliderCrank.h \
    ../Classes/Box2DTestBed/Tests/SphereStack.h \
    ../Classes/Box2DTestBed/Tests/TheoJansen.h \
    ../Classes/Box2DTestBed/Tests/Tiles.h \
    ../Classes/Box2DTestBed/Tests/TimeOfImpact.h \
    ../Classes/Box2DTestBed/Tests/Tumbler.h \
    ../Classes/Box2DTestBed/Tests/VaryingFriction.h \
    ../Classes/Box2DTestBed/Tests/VaryingRestitution.h \
    ../Classes/Box2DTestBed/Tests/VerticalStack.h \
    ../Classes/Box2DTestBed/Tests/Web.h

SOURCES += \
    ../Classes/Box2DTestBed/Box2dView.cpp \
    ../Classes/Box2DTestBed/GLES-Render.cpp \
    ../Classes/Box2DTestBed/Test.cpp \
    ../Classes/Box2DTestBed/TestEntries.cpp
