HEADERS += \
    ../Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/CocosBuilderTest.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/LabelTest/LabelTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/LabelTest/LabelTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ParticleSystemTest/ParticleSystemTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ParticleSystemTest/ParticleSystemTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ScrollViewTest/ScrollViewTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/ScrollViewTest/ScrollViewTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/SpriteTest/SpriteTestLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/SpriteTest/SpriteTestLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayer.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackLayerLoader.h \
    ../Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackTestLayer.h \
    ../Classes/ExtensionsTest/CocoStudioArmatureTest/ArmatureScene.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/ComponentsTestScene.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/EnemyController.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/GameOverScene.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/PlayerController.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/ProjectileController.h \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/SceneController.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CocosGUIScene.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CocoStudioGUITest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomGUIScene.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomTest/CustomImageTest/CustomImageTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomTest/CustomParticleWidgetTest/CustomParticleWidgetTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomImageView.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomImageViewReader.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomParticleWidget.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomParticleWidgetReader.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomReader.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/GUIEditorTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIButtonTest/UIButtonTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIButtonTest/UIButtonTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILayoutTest/UILayoutTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILayoutTest/UILayoutTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIListViewTest/UIListViewTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIListViewTest/UIListViewTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScene.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScene_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISceneManager.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISceneManager_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISliderTest/UISliderTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISliderTest/UISliderTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextTest/UITextTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextTest/UITextTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest.h \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest_Editor.h \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/SceneEditorTest.h \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/acts.h \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/cons.h \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/EventDef.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlButtonTest/CCControlButtonTest.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlColourPicker/CCControlColourPickerTest.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlPotentiometerTest/CCControlPotentiometerTest.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlScene.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSliderTest/CCControlSliderTest.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlStepperTest/CCControlStepperTest.h \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSwitchTest/CCControlSwitchTest.h \
    ../Classes/ExtensionsTest/EditBoxTest/EditBoxTest.h \
    ../Classes/ExtensionsTest/ExtensionsTest.h \
    ../Classes/ExtensionsTest/NetworkTest/HttpClientTest.h \
    ../Classes/ExtensionsTest/NetworkTest/SocketIOTest.h \
    ../Classes/ExtensionsTest/NetworkTest/WebSocketTest.h \
    ../Classes/ExtensionsTest/NotificationCenterTest/NotificationCenterTest.h \
    ../Classes/ExtensionsTest/Scale9SpriteTest/Scale9SpriteTest.h \
    ../Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.h \
    ../Classes/ExtensionsTest/TableViewTest/TableViewTestScene.h \

SOURCES += \
    ../Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsTestLayer.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayer.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/CocosBuilderTest.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayer.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayer.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayer.cpp \
    ../Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackTestLayer.cpp \
    ../Classes/ExtensionsTest/CocoStudioArmatureTest/ArmatureScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/ComponentsTestScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/EnemyController.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/GameOverScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/PlayerController.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/ProjectileController.cpp \
    ../Classes/ExtensionsTest/CocoStudioComponentsTest/SceneController.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CocosGUIScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CocoStudioGUITest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomGUIScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomTest/CustomImageTest/CustomImageTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomTest/CustomParticleWidgetTest/CustomParticleWidgetTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomImageView.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomImageViewReader.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomParticleWidget.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomParticleWidgetReader.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/CustomWidget/CustomReader.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/GUIEditorTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIButtonTest/UIButtonTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIButtonTest/UIButtonTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILayoutTest/UILayoutTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILayoutTest/UILayoutTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIListViewTest/UIListViewTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIListViewTest/UIListViewTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScene.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScene_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISceneManager.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISceneManager_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISliderTest/UISliderTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UISliderTest/UISliderTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextTest/UITextTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UITextTest/UITextTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest_Editor.cpp \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/SceneEditorTest.cpp \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/acts.cpp \
    ../Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/cons.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlButtonTest/CCControlButtonTest.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlColourPicker/CCControlColourPickerTest.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlPotentiometerTest/CCControlPotentiometerTest.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlScene.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSliderTest/CCControlSliderTest.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlStepperTest/CCControlStepperTest.cpp \
    ../Classes/ExtensionsTest/ControlExtensionTest/CCControlSwitchTest/CCControlSwitchTest.cpp \
    ../Classes/ExtensionsTest/EditBoxTest/EditBoxTest.cpp \
    ../Classes/ExtensionsTest/ExtensionsTest.cpp \
    ../Classes/ExtensionsTest/NetworkTest/HttpClientTest.cpp \
    ../Classes/ExtensionsTest/NetworkTest/SocketIOTest.cpp \
    ../Classes/ExtensionsTest/NetworkTest/WebSocketTest.cpp \
    ../Classes/ExtensionsTest/NotificationCenterTest/NotificationCenterTest.cpp \
    ../Classes/ExtensionsTest/Scale9SpriteTest/Scale9SpriteTest.cpp \
    ../Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.cpp \
    ../Classes/ExtensionsTest/TableViewTest/TableViewTestScene.cpp \
